<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\**" />
    <EmbeddedResource Remove="Components\**" />
    <None Remove="Components\**" />
    <Page Remove="Components\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Service\FakeWQTRToUIWQTR.cs" />
    <Compile Remove="ViewModels\WindPanelVM.cs" />
    <Compile Remove="Views\Components\Base\CapsuleBorder.xaml.cs" />
    <Compile Remove="Views\Components\Base\CustomGrid.cs" />
    <Compile Remove="Views\Components\WindDirectionSpeedControl.xaml.cs" />
    <Compile Remove="Views\Components\WindIndicator.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="关闭.png" />
    <None Remove="屏幕截图 2025-11-24 214001.png" />
    <None Remove="灯光系统.png" />
    <None Remove="落地.png" />
    <None Remove="起飞.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="DarkTheme.xaml" />
    <Page Remove="LightTheme.xaml" />
    <Page Remove="Views\Components\Base\CapsuleBorder.xaml" />
    <Page Remove="Views\Components\WindDirectionSpeedControl.xaml" />
    <Page Remove="Views\Components\WindIndicator.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
    <PackageReference Include="WindowsAPICodePack" Version="8.0.15" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="DarkTheme.xaml" />
    <Resource Include="LightTheme.xaml" />
    <Resource Include="关闭.png" />
    <Resource Include="屏幕截图 2025-11-24 214001.png" />
    <Resource Include="灯光系统.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="落地.png" />
    <Resource Include="起飞.png" />
  </ItemGroup>

</Project>
