<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\Base\CapsuleBorder.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="屏幕截图 2025-11-24 214001.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Components\Base\CapsuleBorder.xaml" />
    <Page Remove="DarkTheme.xaml" />
    <Page Remove="LightTheme.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="DarkTheme.xaml" />
    <Resource Include="LightTheme.xaml" />
    <Resource Include="屏幕截图 2025-11-24 214001.png" />
  </ItemGroup>

</Project>
